# Generated by Django 5.0 on 2023-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_detail', models.CharField(max_length=500)),
                ('parent_task_id', models.IntegerField(max_length=10)),
                ('cost_time', models.TimeField()),
                ('deadline_date', models.DateField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
