# Generated by Django 5.0 on 2024-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
