# Generated by Django 5.0 on 2024-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_parent_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
