# Generated by Django 5.0 on 2024-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_parent_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
