# Generated by Django 5.0 on 2024-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_deadline_date_alter_task_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost_time',
            field=models.IntegerField(),
        ),
    ]
