# Generated by Django 5.0 on 2024-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_cost_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost_time',
            field=models.IntegerField(null=True),
        ),
    ]
